//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfCoreLearnEd
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbEntityEntities : DbContext
    {
        public DbEntityEntities()
            : base("name=DbEntityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLDERSLER> TBLDERSLER { get; set; }
        public virtual DbSet<TBLNOTLAR> TBLNOTLAR { get; set; }
        public virtual DbSet<TBLOGRENCI> TBLOGRENCI { get; set; }
        public virtual DbSet<TBLKULUPLER> TBLKULUPLER { get; set; }
    
        public virtual ObjectResult<notlistesi_Result> notlistesi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<notlistesi_Result>("notlistesi");
        }
    
        public virtual ObjectResult<notlist_Result> notlist()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<notlist_Result>("notlist");
        }
    
        public virtual ObjectResult<notlist1_Result> notlist1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<notlist1_Result>("notlist1");
        }
    }
}
